name: Progress Log Check

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: read

jobs:
  ensure-progress-log:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR labels and files
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              core.info('No PR context. Skipping.');
              return;
            }
            const labels = (pr.labels || []).map(l => (l.name || '').toLowerCase());
            const needsCheck = labels.includes('feature') || labels.includes('fix');
            if (!needsCheck) {
              core.info(`Skipping progress check. Labels: ${labels.join(', ')}`);
              return;
            }
            const { owner, repo } = context.repo;
            const files = await github.paginate(github.rest.pulls.listFiles, { owner, repo, pull_number: pr.number, per_page: 100 });
            const changed = files.map(f => f.filename);
            const hasProgress = changed.includes('LATEST_PROGRESS.md');
            if (!hasProgress) {
              core.setFailed('Please prepend LATEST_PROGRESS.md with a new entry for this PR (What changed, Why, Notes, Follow-ups).');
            } else {
              core.info('LATEST_PROGRESS.md update detected.');
            }
